version: "3.11"

services:
  db:
    image: postgres:15
    container_name: db_app
    networks:
      - my_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p 5440
    expose:
      - 5440
    env_file:
      - ${ENV_FILE}


  app:
    build:
      context: .
    env_file:
      - ${ENV_FILE}
    container_name: shava-app
    ports:
      - 443:443
    volumes:
      - media:/media
    command: sh entrypoint.sh
    networks:
      - my_network
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - my_network
    depends_on:
      - db
    restart: always


volumes:
  media:

networks:
  my_network:
